"use client";

import { Amplify } from "aws-amplify";
import outputs from "@/amplify_outputs.json";
import "@aws-amplify/ui-react/styles.css";

/**
 * Configures the Amplify client on the frontend.
 *
 * `amplify_outputs.json` is generated by the Amplify backend build (Amplify Hosting)
 * or a local `npx ampx sandbox`. A placeholder file is used for local UI development
 * so that the marketing site and portal wireframes render without a deployed backend.
 */
try {
  Amplify.configure(outputs as never, { ssr: true });
} catch (error) {
  console.warn("Amplify configuration skipped:", error);
}

export default function ConfigureAmplify() {
  return null;
}
